/*
Created: 26.11.2022
Modified: 30.12.2022
Model: Gokarty model fizyczny
Database: PostgreSQL 12
*/

-- Drop foreign keys (relationships) section ---------------------------------------------------

ALTER TABLE "gokarty"."app_user_role" DROP CONSTRAINT IF EXISTS "FK06"
;
ALTER TABLE "gokarty"."app_user_role" DROP CONSTRAINT IF EXISTS "FK07"
;
ALTER TABLE "gokarty"."reservation" DROP CONSTRAINT IF EXISTS "FK08"
;
ALTER TABLE "gokarty"."reservation" DROP CONSTRAINT IF EXISTS "FK04"
;
ALTER TABLE "gokarty"."invoice" DROP CONSTRAINT IF EXISTS "FK10"
;
ALTER TABLE "gokarty"."email_confirmation_token" DROP CONSTRAINT IF EXISTS "FK05"
;
ALTER TABLE "gokarty"."reservation_kart" DROP CONSTRAINT IF EXISTS "FK02"
;
ALTER TABLE "gokarty"."reservation_kart" DROP CONSTRAINT IF EXISTS "FK03"
;

-- Drop keys section -------------------------------------------------

ALTER TABLE "gokarty"."reservation_kart" DROP CONSTRAINT IF EXISTS "Unique_Identifier10"
;
ALTER TABLE "gokarty"."app_user_role" DROP CONSTRAINT IF EXISTS "Unique_Identifier9"
;
ALTER TABLE "gokarty"."invoice" DROP CONSTRAINT IF EXISTS "Unique_Identifier8"
;
ALTER TABLE "gokarty"."reservation" DROP CONSTRAINT IF EXISTS "PK_reservation"
;
ALTER TABLE "gokarty"."reservation" DROP CONSTRAINT IF EXISTS "AK_reservation_id_reservation"
;
ALTER TABLE "gokarty"."kart" DROP CONSTRAINT IF EXISTS "Unique_Identifier5"
;
ALTER TABLE "gokarty"."track" DROP CONSTRAINT IF EXISTS "Unique_Identifier4"
;
ALTER TABLE "gokarty"."app_role" DROP CONSTRAINT IF EXISTS "Unique_Identifier3"
;
ALTER TABLE "gokarty"."email_confirmation_token" DROP CONSTRAINT IF EXISTS "Unique_Identifier2"
;
ALTER TABLE "gokarty"."app_user" DROP CONSTRAINT IF EXISTS "Unique_Identifier1"
;

-- Drop indexes section -------------------------------------------------

DROP INDEX IF EXISTS "gokarty"."IX_FK05"
;
ALTER TABLE "gokarty"."reservation" DROP CONSTRAINT IF EXISTS "IX_EXC01"
;
ALTER TABLE "gokarty"."reservation_kart" DROP CONSTRAINT IF EXISTS "IX_EXC02"
;

-- Drop tables section ---------------------------------------------------

DROP TABLE IF EXISTS "gokarty"."reservation_kart" CASCADE
;
DROP TABLE IF EXISTS "gokarty"."app_user_role" CASCADE
;
DROP TABLE IF EXISTS "gokarty"."invoice" CASCADE
;
DROP TABLE IF EXISTS "gokarty"."reservation" CASCADE
;
DROP TABLE IF EXISTS "gokarty"."kart" CASCADE
;
DROP TABLE IF EXISTS "gokarty"."track" CASCADE
;
DROP TABLE IF EXISTS "gokarty"."app_role" CASCADE
;
DROP TABLE IF EXISTS "gokarty"."email_confirmation_token" CASCADE
;
DROP TABLE IF EXISTS "gokarty"."app_user" CASCADE
;

-- Drop domain types section ---------------------------------------------------

DROP DOMAIN IF EXISTS "gokarty"."phone"
;

-- Drop user data types section ---------------------------------------------------

DROP TYPE IF EXISTS "gokarty"."Difficulty"
;

-- Drop schemas section ---------------------------------------------------

DROP SCHEMA IF EXISTS "gokarty" CASCADE
;

-- Create schemas section -------------------------------------------------

CREATE SCHEMA "gokarty"
;

-- Create user data types section -------------------------------------------------

CREATE TYPE "gokarty"."Difficulty" AS ENUM
  ( 'Easy', 'Medium', 'Hard' )
;

-- Create domain types section -------------------------------------------------

CREATE DOMAIN "gokarty"."phone" AS Character varying(12) CONSTRAINT "phone_number_constraint" CHECK (VALUE ~ '^([+]\d{2})?\d{9}$')
;

-- Create tables section -------------------------------------------------

-- Table gokarty.app_user

CREATE TABLE "gokarty"."app_user"
(
  "id_app_user" Bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY
    (INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1),
  "name" Character varying(40) NOT NULL,
  "phone" "gokarty"."phone" NOT NULL,
  "email" Character varying NOT NULL
    CHECK ("email" ~ '^\w+@[a-zA-Z_]+?\.[a-zA-Z]{2,3}$'),
  "password" Character varying(255) NOT NULL,
  "locked" Boolean DEFAULT false NOT NULL,
  "enabled" Boolean DEFAULT false
)
WITH (
  autovacuum_enabled=true)
;

ALTER TABLE "gokarty"."app_user" ADD CONSTRAINT "Unique_Identifier1" PRIMARY KEY ("id_app_user")
;

-- Table gokarty.email_confirmation_token

CREATE TABLE "gokarty"."email_confirmation_token"
(
  "id_email_confirmation_token" Bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY
    (INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1),
  "token" Character varying(100) NOT NULL,
  "created_at" Timestamp(6) NOT NULL
    CONSTRAINT "CheckConstraint1" CHECK (created_at <= CURRENT_DATE)
    CONSTRAINT "CheckConstraint2" CHECK (created_at < expires_at),
  "expires_at" Timestamp(6) NOT NULL,
  "confirmed_at" Timestamp(6),
  "id_app_user" Bigint NOT NULL
)
WITH (
  autovacuum_enabled=true)
;

CREATE INDEX "IX_FK05" ON "gokarty"."email_confirmation_token" ("id_app_user")
;

ALTER TABLE "gokarty"."email_confirmation_token" ADD CONSTRAINT "Unique_Identifier2" PRIMARY KEY ("id_email_confirmation_token")
;

-- Table gokarty.app_role

CREATE TABLE "gokarty"."app_role"
(
  "id_app_role" Bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY
    (INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1),
  "name" Character varying(30) NOT NULL
)
WITH (
  autovacuum_enabled=true)
;

ALTER TABLE "gokarty"."app_role" ADD CONSTRAINT "Unique_Identifier3" PRIMARY KEY ("id_app_role")
;

-- Table gokarty.track

CREATE TABLE "gokarty"."track"
(
  "id_track" Bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY
    (INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1),
  "length" Integer NOT NULL
)
WITH (
  autovacuum_enabled=true)
;

ALTER TABLE "gokarty"."track" ADD CONSTRAINT "Unique_Identifier4" PRIMARY KEY ("id_track")
;

-- Table gokarty.kart

CREATE TABLE "gokarty"."kart"
(
  "id_kart" Bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY
    (INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1),
  "name" Character varying(100) NOT NULL,
  "difficulty_level" "gokarty"."Difficulty"
)
WITH (
  autovacuum_enabled=true)
;

ALTER TABLE "gokarty"."kart" ADD CONSTRAINT "Unique_Identifier5" PRIMARY KEY ("id_kart")
;

-- Table gokarty.reservation

CREATE TABLE "gokarty"."reservation"
(
  "id_reservation" Bigint NOT NULL,
  "period" Tsrange NOT NULL
    CONSTRAINT "CheckConstraint1" CHECK (lower(period) <= CURRENT_DATE),
  "id_track" Bigint NOT NULL,
  "id_app_user" Bigint NOT NULL,
  "number_of_people" Integer NOT NULL,
  "cost" Numeric NOT NULL
)
WITH (
  autovacuum_enabled=true)
;

ALTER TABLE "gokarty"."reservation" ADD CONSTRAINT "IX_EXC01" EXCLUDE USING gist (id_app_user WITH =, id_track WITH =, period WITH &&)
;

ALTER TABLE "gokarty"."reservation" ADD CONSTRAINT "PK_reservation" PRIMARY KEY ("period","id_track","id_app_user")
;

ALTER TABLE "gokarty"."reservation" ADD CONSTRAINT "AK_reservation_id_reservation" UNIQUE ("id_reservation")
;

-- Table gokarty.invoice

CREATE TABLE "gokarty"."invoice"
(
  "id_invoice" Bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY
    (INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1),
  "id_reservation" Bigint NOT NULL
)
WITH (
  autovacuum_enabled=true)
;

ALTER TABLE "gokarty"."invoice" ADD CONSTRAINT "Unique_Identifier8" PRIMARY KEY ("id_invoice","id_reservation")
;

-- Table gokarty.app_user_role

CREATE TABLE "gokarty"."app_user_role"
(
  "id_app_user" Bigint NOT NULL,
  "id_app_role" Bigint NOT NULL
)
WITH (
  autovacuum_enabled=true)
;

ALTER TABLE "gokarty"."app_user_role" ADD CONSTRAINT "Unique_Identifier9" PRIMARY KEY ("id_app_user","id_app_role")
;

-- Table gokarty.reservation_kart

CREATE TABLE "gokarty"."reservation_kart"
(
  "id_kart" Bigint NOT NULL,
  "period" Tsrange NOT NULL,
  "id_track" Bigint NOT NULL,
  "id_app_user" Bigint NOT NULL
)
WITH (
  autovacuum_enabled=true)
;

ALTER TABLE "gokarty"."reservation_kart" ADD CONSTRAINT "IX_EXC02" EXCLUDE USING gist (id_kart WITH =, period WITH &&)
;

ALTER TABLE "gokarty"."reservation_kart" ADD CONSTRAINT "Unique_Identifier10" PRIMARY KEY ("id_kart","period","id_track","id_app_user")
;

-- Create foreign keys (relationships) section -------------------------------------------------

ALTER TABLE "gokarty"."app_user_role"
  ADD CONSTRAINT "FK06"
    FOREIGN KEY ("id_app_user")
    REFERENCES "gokarty"."app_user" ("id_app_user")
      ON DELETE NO ACTION
      ON UPDATE NO ACTION
;

ALTER TABLE "gokarty"."app_user_role"
  ADD CONSTRAINT "FK07"
    FOREIGN KEY ("id_app_role")
    REFERENCES "gokarty"."app_role" ("id_app_role")
      ON DELETE NO ACTION
      ON UPDATE NO ACTION
;

ALTER TABLE "gokarty"."reservation"
  ADD CONSTRAINT "FK08"
    FOREIGN KEY ("id_app_user")
    REFERENCES "gokarty"."app_user" ("id_app_user")
      ON DELETE NO ACTION
      ON UPDATE NO ACTION
;

ALTER TABLE "gokarty"."reservation"
  ADD CONSTRAINT "FK04"
    FOREIGN KEY ("id_track")
    REFERENCES "gokarty"."track" ("id_track")
      ON DELETE NO ACTION
      ON UPDATE NO ACTION
;

ALTER TABLE "gokarty"."invoice"
  ADD CONSTRAINT "FK10"
    FOREIGN KEY ("id_reservation")
    REFERENCES "gokarty"."reservation" ("id_reservation")
      ON DELETE NO ACTION
      ON UPDATE NO ACTION
;

ALTER TABLE "gokarty"."email_confirmation_token"
  ADD CONSTRAINT "FK05"
    FOREIGN KEY ("id_app_user")
    REFERENCES "gokarty"."app_user" ("id_app_user")
      ON DELETE NO ACTION
      ON UPDATE NO ACTION
;

ALTER TABLE "gokarty"."reservation_kart"
  ADD CONSTRAINT "FK02"
    FOREIGN KEY ("id_kart")
    REFERENCES "gokarty"."kart" ("id_kart")
      ON DELETE NO ACTION
      ON UPDATE NO ACTION
;

ALTER TABLE "gokarty"."reservation_kart"
  ADD CONSTRAINT "FK03"
    FOREIGN KEY ("period", "id_track", "id_app_user")
    REFERENCES "gokarty"."reservation" ("period", "id_track", "id_app_user")
      ON DELETE NO ACTION
      ON UPDATE NO ACTION
;

-- Grant permissions section -------------------------------------------------

GRANT SELECT ON "gokarty"."app_user" TO "db_reader"
;
GRANT SELECT ON "gokarty"."email_confirmation_token" TO "db_reader"
;
GRANT SELECT ON "gokarty"."app_role" TO "db_reader"
;
GRANT SELECT ON "gokarty"."app_user_role" TO "db_reader"
;
GRANT SELECT ON "gokarty"."invoice" TO "db_reader"
;
GRANT SELECT ON "gokarty"."reservation" TO "db_reader"
;
GRANT SELECT ON "gokarty"."track" TO "db_reader"
;
GRANT SELECT ON "gokarty"."reservation_kart" TO "db_reader"
;
GRANT SELECT ON "gokarty"."kart" TO "db_reader"
;
GRANT SELECT ON "gokarty"."invoice" TO "db_user"
;
GRANT SELECT ON "gokarty"."app_user" TO "db_user"
;
GRANT SELECT ON "gokarty"."reservation" TO "db_user"
;
GRANT SELECT ON "gokarty"."track" TO "db_user"
;
GRANT SELECT ON "gokarty"."kart" TO "db_user"
;
GRANT SELECT ON "gokarty"."email_confirmation_token" TO "db_user"
;
GRANT SELECT ON "gokarty"."invoice" TO "db_privilegeduser"
;
GRANT SELECT ON "gokarty"."app_user" TO "db_privilegeduser"
;
GRANT INSERT ON "gokarty"."app_user" TO "db_privilegeduser"
;
GRANT UPDATE ON "gokarty"."app_user" TO "db_privilegeduser"
;
GRANT SELECT ON "gokarty"."reservation" TO "db_privilegeduser"
;
GRANT INSERT ON "gokarty"."reservation" TO "db_privilegeduser"
;
GRANT UPDATE ON "gokarty"."reservation" TO "db_privilegeduser"
;
GRANT SELECT ON "gokarty"."track" TO "db_privilegeduser"
;
GRANT INSERT ON "gokarty"."track" TO "db_privilegeduser"
;
GRANT UPDATE ON "gokarty"."track" TO "db_privilegeduser"
;
GRANT SELECT ON "gokarty"."kart" TO "db_privilegeduser"
;
GRANT INSERT ON "gokarty"."kart" TO "db_privilegeduser"
;
GRANT UPDATE ON "gokarty"."kart" TO "db_privilegeduser"
;
GRANT SELECT ON "gokarty"."email_confirmation_token" TO "db_privilegeduser"
;
GRANT SELECT ON "gokarty"."app_role" TO "db_owner"
;
GRANT INSERT ON "gokarty"."app_role" TO "db_owner"
;
GRANT UPDATE ON "gokarty"."app_role" TO "db_owner"
;
GRANT DELETE ON "gokarty"."app_role" TO "db_owner"
;
GRANT REFERENCES ON "gokarty"."app_role" TO "db_owner"
;
GRANT TRIGGER ON "gokarty"."app_role" TO "db_owner"
;
GRANT TRUNCATE ON "gokarty"."app_role" TO "db_owner"
;
GRANT SELECT ON "gokarty"."app_user_role" TO "db_owner"
;
GRANT INSERT ON "gokarty"."app_user_role" TO "db_owner"
;
GRANT UPDATE ON "gokarty"."app_user_role" TO "db_owner"
;
GRANT DELETE ON "gokarty"."app_user_role" TO "db_owner"
;
GRANT REFERENCES ON "gokarty"."app_user_role" TO "db_owner"
;
GRANT TRIGGER ON "gokarty"."app_user_role" TO "db_owner"
;
GRANT TRUNCATE ON "gokarty"."app_user_role" TO "db_owner"
;
GRANT SELECT ON "gokarty"."email_confirmation_token" TO "db_owner"
;
GRANT INSERT ON "gokarty"."email_confirmation_token" TO "db_owner"
;
GRANT UPDATE ON "gokarty"."email_confirmation_token" TO "db_owner"
;
GRANT DELETE ON "gokarty"."email_confirmation_token" TO "db_owner"
;
GRANT REFERENCES ON "gokarty"."email_confirmation_token" TO "db_owner"
;
GRANT TRIGGER ON "gokarty"."email_confirmation_token" TO "db_owner"
;
GRANT TRUNCATE ON "gokarty"."email_confirmation_token" TO "db_owner"
;
GRANT SELECT ON "gokarty"."app_user" TO "db_owner"
;
GRANT INSERT ON "gokarty"."app_user" TO "db_owner"
;
GRANT UPDATE ON "gokarty"."app_user" TO "db_owner"
;
GRANT DELETE ON "gokarty"."app_user" TO "db_owner"
;
GRANT REFERENCES ON "gokarty"."app_user" TO "db_owner"
;
GRANT TRIGGER ON "gokarty"."app_user" TO "db_owner"
;
GRANT TRUNCATE ON "gokarty"."app_user" TO "db_owner"
;
GRANT SELECT ON "gokarty"."invoice" TO "db_owner"
;
GRANT INSERT ON "gokarty"."invoice" TO "db_owner"
;
GRANT UPDATE ON "gokarty"."invoice" TO "db_owner"
;
GRANT DELETE ON "gokarty"."invoice" TO "db_owner"
;
GRANT REFERENCES ON "gokarty"."invoice" TO "db_owner"
;
GRANT TRIGGER ON "gokarty"."invoice" TO "db_owner"
;
GRANT TRUNCATE ON "gokarty"."invoice" TO "db_owner"
;
GRANT SELECT ON "gokarty"."track" TO "db_owner"
;
GRANT INSERT ON "gokarty"."track" TO "db_owner"
;
GRANT UPDATE ON "gokarty"."track" TO "db_owner"
;
GRANT DELETE ON "gokarty"."track" TO "db_owner"
;
GRANT REFERENCES ON "gokarty"."track" TO "db_owner"
;
GRANT TRIGGER ON "gokarty"."track" TO "db_owner"
;
GRANT TRUNCATE ON "gokarty"."track" TO "db_owner"
;
GRANT SELECT ON "gokarty"."reservation" TO "db_owner"
;
GRANT INSERT ON "gokarty"."reservation" TO "db_owner"
;
GRANT UPDATE ON "gokarty"."reservation" TO "db_owner"
;
GRANT DELETE ON "gokarty"."reservation" TO "db_owner"
;
GRANT REFERENCES ON "gokarty"."reservation" TO "db_owner"
;
GRANT TRIGGER ON "gokarty"."reservation" TO "db_owner"
;
GRANT TRUNCATE ON "gokarty"."reservation" TO "db_owner"
;
GRANT SELECT ON "gokarty"."reservation_kart" TO "db_owner"
;
GRANT INSERT ON "gokarty"."reservation_kart" TO "db_owner"
;
GRANT UPDATE ON "gokarty"."reservation_kart" TO "db_owner"
;
GRANT DELETE ON "gokarty"."reservation_kart" TO "db_owner"
;
GRANT REFERENCES ON "gokarty"."reservation_kart" TO "db_owner"
;
GRANT TRIGGER ON "gokarty"."reservation_kart" TO "db_owner"
;
GRANT TRUNCATE ON "gokarty"."reservation_kart" TO "db_owner"
;
GRANT SELECT ON "gokarty"."kart" TO "db_owner"
;
GRANT INSERT ON "gokarty"."kart" TO "db_owner"
;
GRANT UPDATE ON "gokarty"."kart" TO "db_owner"
;
GRANT DELETE ON "gokarty"."kart" TO "db_owner"
;
GRANT REFERENCES ON "gokarty"."kart" TO "db_owner"
;
GRANT TRIGGER ON "gokarty"."kart" TO "db_owner"
;
GRANT TRUNCATE ON "gokarty"."kart" TO "db_owner"
;
GRANT SELECT ON "gokarty"."app_user" TO "db_authenticator"
;
GRANT SELECT ON "gokarty"."email_confirmation_token" TO "db_authenticator"
;

